### ISSUE TITLE
Prihlasenie uzivatelov [4h]

### ISSUE THREAD

**Issue by darjanin** [darjanin/xp-library#2]
Prihlasenie uzivatela bude zabezpecene pomocou emailu uzivatela alebo socialnych sieti facebook.

**Comment by OndrejRitomsky** [comment]
Ondrej, Adam

**Comment by OndrejRitomsky** [comment]
Testy este niesu
Dostavame hlasku ze modifikujeme prototype a ze to spomaluje stranku, neviem ale kde mu to vadi

**Comment by darjanin** [comment]
Vloz sem presny vypis co to robi alebo nieco podla coho viem hladat.

**Comment by darjanin** [comment]
Zaroven preco ste vytvorili novy priecinok `js`???? Vsetko je javascript takze aj taketo help funkcie mali ist do `src`.

**Comment by darjanin** [comment]
Pokial do premennej vlozite nieco co sa urcite nezmeni (ako firebase url) tak pouzi `const`.

**Comment by darjanin** [comment]
Skuste pouzit nejake menej sifrovane nazvy miestami. Miesto `loginWithPW` pouzit `loginWithPassword` je ihned zrejme co to robi. Ako skratku pre heslo som zvyknuty pouzivat `pass` ked uz treba. Ale nie je to vyzadovane. Radsej napiste par znakov navyse.

Presne taketo setrenie znakov vytvara dovody preco sa pouzivaju potom komentare. Kod sam o sebe by mal povedat co robi. Potom komentare su zbytocnost a to chcete dosiahnut.

**Comment by OndrejRitomsky** [comment]
Hej tie skratky, tiez som za ich zrusenie, dik za upozornenie.
Ale tiez by sme mohli zrusit "e" (error, event?) (e, evt, event ... aby to bolo konzistentne)

Pri loadnuti stranky, ale len vo firefoxe (warning)
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

takze mozno je to ok... Chrome ani edge to nepisu
